### ISSUE TITLE
joe-v2-subraph seems to be missing

### ISSUE THREAD

**Issue by zkR0ller** [traderjoe-xyz/dexcandles-v2#7]
First of all: The V2 looks really great and is really really interesting!

Is there any chance that you can also publish the v2-subgraph? I only see the dexcandles but in the docs you mention two subgraphs:
https://docs.traderjoexyz.com/subgraphs/avalanche

Thanky you!

**Comment by gaepsuni** [comment]
Hi, you can find it here: https://github.com/traderjoe-xyz/joe-subgraph-v2
